
elasticsearch:
  image: elasticsearch:7.3.1
  environment:
   - discovery.type=single-node
  ports:
   - "9200:9200"

logstash:
  build: ./logstash/
  links:
    - elasticsearch
  ports:
    - "5959:5959"
    - "9092:9092"

kibana:
  image: kibana:7.3.1
  links:
    - elasticsearch
  ports:
    - "5601:5601"