
elasticsearch:
  image: elasticsearch:5.0
  ports:
   - "9200:9200"

logstash:
  build: ./logstash/
  links:
    - elasticsearch

kibana:
  image: kibana:5.0
  links:
    - elasticsearch
  ports:
    - "5601:5601"